# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    password_recovery:
        class: AppBundle\Services\PasswordRecovery\PasswordRecoveryService
        autowire: true
#        arguments: ["@service_container", "@doctrine.orm.entity_manager"]
    form_utils:
        class: AppBundle\Services\PasswordRecovery\FormUtilsService
    recovery:
        class: AppBundle\Services\PasswordRecovery\Recovery
        autowire: true
    email:
        class: AppBundle\Services\PasswordRecovery\SendEmail
        autowire: true
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }
    dql_for_knp_paginator:
        class: AppBundle\Services\DQL\DqlForKnpPaginator
    dql_for_category_menu:
        class: AppBundle\Services\DQL\DqlForCategoryMenu
    search_article:
        class: AppBundle\Services\Search\SearchService
        autowire: true
